In [4]:
import time
import random
import gym
import numpy as np
import pedgrid
from pedgrid.wrappers import *
from pedgrid.agents import PedAgent

In [5]:
%matplotlib auto
%load_ext autoreload
%autoreload 2

Using matplotlib backend: QtAgg
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
# Load the gym environment
env = gym.make('MultiPedestrian-Empty-20x80-v0')
agents = []
for i in range(50):
    yPos = np.random.randint(2, 18)
    xPos = np.random.randint(10, 18)
    direction = 2 if np.random.random() > 0.5 else 0
    prob = np.random.random()
    if prob < 0.1:
        speed = 1
    elif prob < 0.9:
        speed = 2
    else:
        speed = 3
    agents.append(PedAgent((xPos, yPos), direction, speed))
env.addAgents(agents)


In [7]:
env.reset()

{}

In [9]:

for i in range(0, 20):

    obs, reward, done, info = env.step(None)
    
    if done:
        "Reached the goal"
        break

    env.render()

    time.sleep(0.5)

gaps [[2 8 4]
 [2 8 4]
 [0 0 0]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [0 0 0]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [2 8 4]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[1 8 4]
 [0 0 0]
 [1 8 4]]
maxgap 1
0 1 8 4
gaps [[2 8 4]
 [0 0 0]
 [2 8 4]]
maxgap 2
2 2 8 4
gaps [[2 8 4]
 [2 8 4]
 [0 0 0]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [2 8 4]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [2 8 4]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [0 0 0]
 [0 0 0]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [2 8 4]
 [2 8 4]]
maxgap 2
1 2 8 4
gaps [[3 8 4]
 [3 8 4]
 [0 0 0]]
maxgap 3
0 3 8 4
gaps [[2 8 4]
 [2 8 4]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [2 8 4]
 [0 0 0]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [0 0 0]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [0 0 0]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [2 8 4]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [2 8 4]
 [0 0 0]]
maxgap 2
0 2 8 4
gaps [[3 8 4]
 [0 0 0]
 [0 0 0]]
maxgap 3
0 3 8 4
gaps [[2 8 4]
 [2 8 4]
 [2 8 4]]
maxgap 2
0 2 8 4
gaps [[2 8 4]
 [0 0 0]
 [2 8 4]]
maxgap 2
0 2 8 4


AssertionError: 

In [ ]:
# Test the close method
env.close()
